#!/usr/bin/env node
// @ts-check
// Generates a double-clickable macOS app bundle (dist/nudgit.app): a
// stay-open AppleScript applet (built with `osacompile -s`, no packaging
// dependencies) that starts nudgit's launcher-mode server in the
// background, watches it while the app is open, and stops it again when the
// app quits. The bundle is self-contained: the runtime files are copied into
// Contents/Resources/nudgit/ so it can be moved anywhere (e.g. dragged to
// /Applications) without depending on this repo checkout.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

if (process.platform !== 'darwin') {
  console.error('npm run app only builds a macOS app bundle; this is not macOS.');
  process.exit(1);
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const APP_NAME = 'nudgit';
const BUNDLE_ID = 'io.github.bl0rb.nudgit';

const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf-8'));

const distDir = path.join(REPO_ROOT, 'dist');
const appDir = path.join(distDir, `${APP_NAME}.app`);
const contentsDir = path.join(appDir, 'Contents');
const resourcesDir = path.join(contentsDir, 'Resources');
const runtimeDir = path.join(resourcesDir, 'nudgit');

// Stay-open AppleScript applet. Reads its own bundle path at runtime (`path
// to me`), so nothing here is repo- or machine-specific.
const APPLESCRIPT_SOURCE = `-- Generated by scripts/make-app.js — do not edit by hand, regenerate instead
-- with "npm run app".
--
-- Stay-open AppleScript applet: starts nudgit's launcher-mode server in
-- the background on launch, watches it while the app is open, and stops it
-- again when the app quits.

property nodePID : ""

on run
	set nodePath to my findNodeBinary()
	if nodePath is "" then
		my showNodeMissingDialog()
		quit
		return
	end if

	set resourcesPath to (POSIX path of (path to me)) & "Contents/Resources/nudgit/"
	set scriptPath to resourcesPath & "bin/nudgit.js"
	set homePath to POSIX path of (path to home folder)
	set logPath to homePath & "Library/Logs/nudgit.log"

	set cmd to "cd " & quoted form of homePath & " && exec " & quoted form of nodePath & " " & quoted form of scriptPath & " > " & quoted form of logPath & " 2>&1 & echo $!"
	set nodePID to do shell script cmd
end run

on idle
	if nodePID is not "" then
		set stillAlive to false
		try
			do shell script "kill -0 " & nodePID & " 2>/dev/null"
			set stillAlive to true
		end try
		if not stillAlive then
			quit
		end if
	end if
	return 2
end idle

on reopen
	try
		do shell script "open http://localhost:4400/__uce/"
	end try
end reopen

on quit
	if nodePID is not "" then
		try
			do shell script "kill -TERM " & nodePID & " 2>/dev/null"
		end try
		delay 1.5
		try
			do shell script "kill -0 " & nodePID & " 2>/dev/null"
			-- kill -0 above did not throw, so the process is still alive.
			try
				do shell script "kill -KILL " & nodePID & " 2>/dev/null"
			end try
		end try
	end if
	continue quit
end quit

on findNodeBinary()
	set foundNode to ""
	try
		set viaShell to do shell script "/bin/zsh -lc 'command -v node' 2>/dev/null"
		if viaShell is not "" then set foundNode to my validNodeOrEmpty(viaShell)
	end try
	if foundNode is not "" then return foundNode

	repeat with fixedPath in {"/opt/homebrew/bin/node", "/usr/local/bin/node"}
		set foundNode to my validNodeOrEmpty(fixedPath as string)
		if foundNode is not "" then return foundNode
	end repeat

	try
		set nvmGlob to (POSIX path of (path to home folder)) & ".nvm/versions/node/*/bin/node"
		set nvmNode to do shell script "ls -d " & nvmGlob & " 2>/dev/null | sort -V | tail -n 1"
		if nvmNode is not "" then
			set foundNode to my validNodeOrEmpty(nvmNode)
			if foundNode is not "" then return foundNode
		end if
	end try

	set voltaNode to (POSIX path of (path to home folder)) & ".volta/bin/node"
	set foundNode to my validNodeOrEmpty(voltaNode)
	if foundNode is not "" then return foundNode

	return ""
end findNodeBinary

on validNodeOrEmpty(candidatePath)
	try
		do shell script "test -x " & quoted form of candidatePath
	on error
		return ""
	end try
	try
		set verStr to do shell script quoted form of candidatePath & " -v"
		if my majorVersionOf(verStr) ≥ 22 then return candidatePath
	end try
	return ""
end validNodeOrEmpty

on majorVersionOf(verStr)
	if verStr starts with "v" then set verStr to text 2 thru -1 of verStr
	set oldDelims to AppleScript's text item delimiters
	set AppleScript's text item delimiters to "."
	set parts to text items of verStr
	set AppleScript's text item delimiters to oldDelims
	try
		return (item 1 of parts) as integer
	on error
		return 0
	end try
end majorVersionOf

on showNodeMissingDialog()
	set isGerman to false
	try
		set isGerman to (user locale of (system info)) starts with "de"
	end try
	if isGerman then
		set msgText to "Node.js (Version 22 oder neuer) wurde nicht gefunden. nudgit benötigt Node.js, um zu starten."
		set btnDownload to "Node.js herunterladen"
		set btnCancel to "Abbrechen"
	else
		set msgText to "Node.js (version 22 or newer) was not found. nudgit needs Node.js to run."
		set btnDownload to "Download Node.js"
		set btnCancel to "Cancel"
	end if
	try
		set btnResult to button returned of (display dialog msgText buttons {btnCancel, btnDownload} default button btnDownload)
		if btnResult is btnDownload then open location "https://nodejs.org"
	end try
end showNodeMissingDialog
`;

fs.rmSync(appDir, { recursive: true, force: true });
fs.mkdirSync(distDir, { recursive: true });

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nudgit-app-'));
const scriptPath = path.join(tmpDir, `${APP_NAME}.applescript`);
fs.writeFileSync(scriptPath, APPLESCRIPT_SOURCE, 'utf-8');

try {
  execFileSync('osacompile', ['-s', '-o', appDir, scriptPath], { stdio: 'inherit' });
} finally {
  fs.rmSync(tmpDir, { recursive: true, force: true });
}

// Copy the runtime files so the bundle is self-contained and relocatable.
fs.mkdirSync(runtimeDir, { recursive: true });
fs.cpSync(path.join(REPO_ROOT, 'bin'), path.join(runtimeDir, 'bin'), { recursive: true });
fs.cpSync(path.join(REPO_ROOT, 'src'), path.join(runtimeDir, 'src'), { recursive: true });
fs.cpSync(path.join(REPO_ROOT, 'package.json'), path.join(runtimeDir, 'package.json'));
fs.cpSync(path.join(REPO_ROOT, 'README.md'), path.join(runtimeDir, 'README.md'));
const licensePath = path.join(REPO_ROOT, 'LICENSE');
if (fs.existsSync(licensePath)) {
  fs.cpSync(licensePath, path.join(runtimeDir, 'LICENSE'));
}

// Fill in the bundle identity; osacompile only sets CFBundleName (from the
// output filename).
const infoPlistPath = path.join(contentsDir, 'Info.plist');
const plistEdits = [
  ['CFBundleName', APP_NAME],
  ['CFBundleDisplayName', APP_NAME],
  ['CFBundleIdentifier', BUNDLE_ID],
  ['CFBundleShortVersionString', pkg.version],
];
for (const [key, value] of plistEdits) {
  execFileSync('plutil', ['-replace', key, '-string', value, infoPlistPath], { stdio: 'inherit' });
}

// App icon: replace osacompile's default applet.icns. osacompile also sets
// CFBundleIconName, which newer macOS versions prefer and resolve from the
// default Assets.car (the generic AppleScript icon) — remove both so macOS
// falls back to CFBundleIconFile ("applet" → applet.icns).
fs.cpSync(path.join(REPO_ROOT, 'assets', 'nudgit.icns'), path.join(resourcesDir, 'applet.icns'));
fs.rmSync(path.join(resourcesDir, 'Assets.car'), { force: true });
try {
  execFileSync('plutil', ['-remove', 'CFBundleIconName', infoPlistPath], { stdio: 'ignore' });
} catch {
  // key not present (older osacompile) — nothing to remove
}

// Re-sign: adding resources after osacompile's own signing step invalidates
// its signature. Ad-hoc (`-s -`) is enough to run locally and to be
// distributed unnotarized; see the README's Gatekeeper note.
execFileSync('codesign', ['--force', '--deep', '-s', '-', appDir], { stdio: 'inherit' });

console.log(`App created: ${appDir}`);
console.log('Can be moved to /Applications via drag & drop.');
